apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-deployment
spec:
  replicas: 1 # KEDA(Kubernetes Event-driven Autoscaling)가 관리하므로 시작은 1개 (또는 0개로 설정 가능)
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: celery-worker:local
        imagePullPolicy: IfNotPresent #로컬 이미지 사용
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        resources:
          requests:
            cpu: "100m"    # 0.1 CPU 코어
            memory: "128Mi" # 128 Mebibytes
          limits:
            cpu: "500m"
            memory: "512Mi"