apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi_app
  template:
    metadata:
      labels:
        app: fastapi_app
    spec:
      containers:
        - name: fastapi-api
          image: fastapi_app
          imagePullPolicy: IfNotPresent #로컬 이미지 사용
          command: ["uvicorn", "fast_api.app:app", "--host", "0.0.0.0", "--port", "8000"]
          env:
            - name: REDIS_URL
              value: "redis://redis-service:6379/0"
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"