apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer # Minikube 환경에서는 LoadBalancer 타입이 편리합니다.